### PR TITLE
feat: add LIC 12 (#16)

### LINKED ISSUE #16: LIC #12

### PR DESCRIPTION
**Pull request by mdinler**
Closes #16

### CODE REVIEW

**Review by nichujie — APPROVED** [review]

**Comment by ekner** [comment]
Why can't K_PTS = 0?

**Comment by mdinler** [comment]
@ekner I was a bit unsure myself, but LIC 7 had that restriction so I assumed it was the same for this one. What do you think? Should I remove it?

**Comment by ekner** [comment]
@mdinler Maybe that's safest?

**Comment by nichujie** [comment]
I guess it's better to have K_PTS>0. Otherwise LIC7 will be equivalent to LIC0, and LIC12 will be similar to them. We can state this in Readme.

**Pull request merged**
